CONFIG_DONGLE_SCREEN_HORIZONTAL=y
CONFIG_DONGLE_SCREEN_FLIPPED=n
CONFIG_DONGLE_SCREEN_AMBIENT_LIGHT=n
CONFIG_DONGLE_SCREEN_LAYER_ACTIVE=y
CONFIG_DONGLE_SCREEN_MODIFIER_ACTIVE=y
CONFIG_DONGLE_SCREEN_WPM_ACTIVE=y

CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y

CONFIG_ZMK_SLEEP=n


# From zmk-pointing-acceleration-alpha. Enable the acceleration module.
# https://github.com/nuovotaka/zmk-pointing-acceleration-alpha
CONFIG_ZMK_INPUT_PROCESSOR_ACCELERATION=y
# Choose your level (1 or 2)
# CONFIG_INPUT_PROCESSOR_ACCEL_LEVEL_SIMPLE=y      # Level 1: Simple
# CONFIG_INPUT_PROCESSOR_ACCEL_LEVEL_STANDARD=y  # Level 2: Standard
# CONFIG_INPUT_PROCESSOR_ACCEL_PRESET_GAMING_LASER=y       # Gaming laser mouse
# CONFIG_INPUT_PROCESSOR_ACCEL_PRESET_OFFICE_OPTICAL=y   # Office optical mouse
# CONFIG_INPUT_PROCESSOR_ACCEL_PRESET_HIGH_SENS_TRACKBALL=y # High sensitivity trackball
CONFIG_INPUT_PROCESSOR_ACCEL_PRESET_CUSTOM=y