# Boost BLE signal
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Decrease chatter; increase latency, but increase stability
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=8
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=8

# From zmk-pointing-acceleration-alpha. Enable the acceleration module.
# https://github.com/nuovotaka/zmk-pointing-acceleration-alpha
CONFIG_ZMK_INPUT_PROCESSOR_ACCELERATION=y
# Choose your level (1 or 2)
# CONFIG_INPUT_PROCESSOR_ACCEL_LEVEL_SIMPLE=y      # Level 1: Simple
# CONFIG_INPUT_PROCESSOR_ACCEL_LEVEL_STANDARD=y  # Level 2: Standard
# CONFIG_INPUT_PROCESSOR_ACCEL_PRESET_GAMING_LASER=y       # Gaming laser mouse
# CONFIG_INPUT_PROCESSOR_ACCEL_PRESET_OFFICE_OPTICAL=y   # Office optical mouse
# CONFIG_INPUT_PROCESSOR_ACCEL_PRESET_HIGH_SENS_TRACKBALL=y # High sensitivity trackball
CONFIG_INPUT_PROCESSOR_ACCEL_PRESET_CUSTOM=y